development:
  adapter: mysql2
  encoding: utf8
  database: devices_development
  username: root
  password: toor
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
<<<<<<< HEAD
  database: devices_testing
=======
  database: devices_development
>>>>>>> 53a75de68dd6fca626b398c21d1923a2b7056408
  username: root
  password: toor
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: devices_production
  username: root
  password: toor
  host: localhost
